# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.cache/wt [current_project]
set_property parent.project_path /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/Counter.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/ReceiverController.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/Register.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/Shift_Reg.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/Shift_Reg_Rx.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/imports/rx_v1/sources_1/new/Top_Rx.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/Trans/Top_Trans.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/Trans/Trans2.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/Trans/TransmitionController.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_Rx/project_1_Rx.srcs/sources_1/new/UART_Receiver.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_UART/project_1_UART.srcs/sources_1/new/baud_rate_gen2.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/imports/project_1_UART/project_1_UART.srcs/sources_1/new/clk_divider.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/counter_n_bit.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/decoder.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/sev_seg_controller.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/seven_seg_decoder.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/top_UART.sv
  /home/it/Desktop/Backloop/UART_Tx_Rx/UART_Tx_Rx.srcs/sources_1/new/TOP.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/it/Downloads/pin-assignment.xdc
set_property used_in_implementation false [get_files /home/it/Downloads/pin-assignment.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
